apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: mjorod/udagram-frontend:v2
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
